In [28]:
import pandas as pd
import numpy as np
text =['Honored as “rocket force a science and technology experts,',
    '” the Zhang and his a fellow experts ',
    'from private a companies will']

In [34]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfTransformer

In [30]:
cv = CountVectorizer(stop_words='english')
sparsed_matrix=cv.fit_transform(text)

In [31]:
sparsed_matrix.todense()

matrix([[0, 1, 0, 1, 1, 0, 1, 1, 1, 0],
        [0, 1, 1, 0, 0, 0, 0, 0, 0, 1],
        [1, 0, 0, 0, 0, 1, 0, 0, 0, 0]])

In [32]:
cv.vocabulary_

{'honored': 4,
 'rocket': 6,
 'force': 3,
 'science': 7,
 'technology': 8,
 'experts': 1,
 'zhang': 9,
 'fellow': 2,
 'private': 5,
 'companies': 0}

In [36]:
#stop words 
tfidf_transformer = TfidfTransformer()
result= tfidf_transformer.fit_transform(sparsed_matrix)

In [37]:
result.todense()

matrix([[0.        , 0.32200242, 0.        , 0.42339448, 0.42339448,
         0.        , 0.42339448, 0.42339448, 0.42339448, 0.        ],
        [0.        , 0.4736296 , 0.62276601, 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.62276601],
        [0.70710678, 0.        , 0.        , 0.        , 0.        ,
         0.70710678, 0.        , 0.        , 0.        , 0.        ]])

In [38]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer(stop_words='english')
sparsed_matrix=tfidf_vectorizer.fit_transform(text)
sparsed_matrix.todense()

matrix([[0.        , 0.32200242, 0.        , 0.42339448, 0.42339448,
         0.        , 0.42339448, 0.42339448, 0.42339448, 0.        ],
        [0.        , 0.4736296 , 0.62276601, 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.62276601],
        [0.70710678, 0.        , 0.        , 0.        , 0.        ,
         0.70710678, 0.        , 0.        , 0.        , 0.        ]])