In [ ]:
import numpy as np
import pandas 
my_data=np.random.randint(0,101,(4,3))
print(my_data)
myindex=['CA','NY','TX']
my_columns=['Jan','Feb','Mar']
print(df)
np.




[[52 60 47]
 [29 60 53]
 [11 40 91]
 [45 97 24]]
    0   1   2
0  57  77  46
1   3  46  29
2  86  21  21
3  81  23  94
