In [1]:
import pandas as pd
import numpy as np
my_index = ["USA","Xnanda","IK" ]
my_array = [0,1,2]
# np.arange(0,4).shape(1)
ass = pd.Series(data=my_array,index=my_index)
ass["IK"]



np.int64(2)

In [2]:
age={"jhon":5,"frank":20,"spike":9}

pd.Series(age)

jhon      5
frank    20
spike     9
dtype: int64

In [3]:
#Dataframe
q1={"brazil":256,"africa":534,"USA":546,"CHINA":2454}

q2={"brazil":256,"africa":534,"USA":546,"CHINA":2454}
sr1=pd.Series(q2)
sr2=pd.Series(q2)
# data=pd.DataFrame()

sr1 * 100
sr1 + sr2

brazil     512
africa    1068
USA       1092
CHINA     4908
dtype: int64

In [4]:
sr1["brazil"]
sr1.keys()

Index(['brazil', 'africa', 'USA', 'CHINA'], dtype='object')

In [5]:
first_half=sr2.add(sr1,fill_value=0)


print(first_half)

brazil     512
africa    1068
USA       1092
CHINA     4908
dtype: int64


In [6]:
my_data=np.random.randint(0,101,(4,3))
print(my_data)

myindex=['CA','NY','TX','FL']
my_columns=['Jan','Feb','Mar']
df=pd.DataFrame(my_data,myindex,my_columns)
print(df)


[[36 80 91]
 [27 80 27]
 [88 81 23]
 [56 37 88]]
    Jan  Feb  Mar
CA   36   80   91
NY   27   80   27
TX   88   81   23
FL   56   37   88


In [7]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['New York', 'London', 'Paris']
}
df = pd.DataFrame(data)

# Accessing a column
print(df['Name']) 

# Accessing the first row
print(df.iloc[0]) 

0      Alice
1        Bob
2    Charlie
Name: Name, dtype: object
Name       Alice
Age           25
City    New York
Name: 0, dtype: object


In [8]:

pwd


'c:\\Users\\l\\OneDrive\\Documents\\GenAIPython\\Pandas'

In [9]:
ls


 Volume in drive C is Windows-SSD
 Volume Serial Number is 4019-E854

 Directory of c:\Users\l\OneDrive\Documents\GenAIPython\Pandas

15/01/2026  16:17    <DIR>          .
15/01/2026  14:30    <DIR>          ..
15/01/2026  17:15            12,355 DateFrame.ipynb
24/01/2026  14:45            26,868 Pandas.ipynb
04/01/2026  21:00             1,713 Pandas_excercise.ipynb
15/01/2026  17:05             1,057 user.csv
               4 File(s)         41,993 bytes
               2 Dir(s)  149,010,157,568 bytes free


In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    3 non-null      object
 1   Age     3 non-null      int64 
 2   City    3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes


In [11]:
import pandas as pd
file=pd.read_csv('user.csv')
# file.to_string()
# file.columns()
# file.head()
# file.tail()
# file.info()
file.describe().transpose()
# file
file=file.set_index('gender')
# file.index
file





KeyError: "None of ['gender'] are in the columns"

In [ ]:
# file.head()
file.reset_index() 
# file=file.set_index('gender')
file.loc['Male'] ## for known 
file.iloc[9] ## unkonwn

first_name                      Misti
last_name                      Fillan
email         mfillan9@friendfeed.com
ip_address               116.231.5.10
date                        2/21/2017
Name: Female, dtype: object

In [ ]:
file.iloc[3:5]

first_name last_name                 email      ip_address        date
gender                                                                       
Male         Arvy    Lempke  alempke3@squidoo.com  117.227.52.135  10/20/2017
Female       Cody     Jakov        cjakov4@i2i.jp  172.197.66.100   5/23/2017

In [ ]:
# fd=file.drop("Male",axis=1)
# print(fd)
file
# one_row=file.iloc[0]
# print(one_row)
# file.insert(one_row)


first_name  last_name                     email      ip_address  \
gender                                                                   
Female    Roobbie    Wilbore    rwilbore0@bandcamp.com   82.243.17.211   
Female  Aprilette       Dole     adole1@altervista.org   12.132.123.75   
Male     Phillipe  Winkworth     pwinkworth2@wufoo.com   71.62.119.246   
Male         Arvy     Lempke      alempke3@squidoo.com  117.227.52.135   
Female       Cody      Jakov            cjakov4@i2i.jp  172.197.66.100   
...           ...        ...                       ...             ...   
Female       Roxy   Adolfson  radolfsong@xinhuanet.com    81.86.118.11   
Female     Catlee     Covert      crth@liveinternet.ru    178.94.55.68   
Female    Raquela    Authers      rauthersi@seesaa.net   36.105.40.130   
Male       Josias     Currum       jcurrumj@meetup.com   39.200.104.21   
Male       Wyndhm    Hullins            whul@github.io  201.148.141.37   

              date  
gender              
Female    1/7/2018  
Female   3/27/2017  
Male     1/20/2018  
Male    10/20/2017  
Female   5/23/2017  
...            ...  
Female  12/18/2017  
Female  11/28/2017  
Female   5/30/2017  
Male     4/11/2017  
Male    11/19/2017  

[1471 rows x 5 columns]

In [ ]:
type(file['email'])

pandas.core.series.Series

In [ ]:
mycols=['email','gender','date']
file[['email','gender','date']]
file.columns


NameError: name 'file' is not defined

In [ ]:
file['uniquegender']=file['date'] + file['date']
print(file.head())



  first_name  last_name                   email  gender      ip_address  \
0    Roobbie    Wilbore  rwilbore0@bandcamp.com  Female   82.243.17.211   
1  Aprilette       Dole   adole1@altervista.org  Female   12.132.123.75   
2   Phillipe  Winkworth   pwinkworth2@wufoo.com    Male   71.62.119.246   
3       Arvy     Lempke    alempke3@squidoo.com    Male  117.227.52.135   
4       Cody      Jakov          cjakov4@i2i.jp  Female  172.197.66.100   

         date          uniquegender  
0    1/7/2018      1/7/20181/7/2018  
1   3/27/2017    3/27/20173/27/2017  
2   1/20/2018    1/20/20181/20/2018  
3  10/20/2017  10/20/201710/20/2017  
4   5/23/2017    5/23/20175/23/2017  


In [ ]:
# file.drop('uniquegender',axis=1,)
# file.drop('uniquegender',axis=1)
# file=file.drop('uniquegender',axis=1)
# print(file)
# file.shape()
file

NameError: name 'file' is not defined

In [ ]:
file

NameError: name 'file' is not defined