In [11]:
import numpy as np
slice_arr=np.arange(1,26).reshape(5,5)
print(slice_arr)
slice_arr[2:,1:]
slice_arr[:3,1:2]
slice_arr[4]
slice_arr.sum(axis=0)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


array([55, 60, 65, 70, 75])

Simulate a 2-layer neural network forward pass manually.
* Input: 5 samples, 3 features → shape (5, 3)
* Layer 1 weights (3,8), bias (8,) — apply sigmoid: 1/(1+np.exp(-x))
* Layer 2 weights (8,1), bias (1,)
* Print output shapes at each step

In [ ]:
import numpy as np
# x=np.random.seed(42)
X = np.random.randn(5, 3)
w= np.random.rand(3,8)
b=np.zeros(8)
z = X @ w + b
A1 = 1 / (1 + np.exp(-z))

print("layer1 ",z)
print("layer1 ",A1.shape)
w1 = np.random.rand(8,1)



b2= np.zeros(1)

y= A1 @ w1 + b2

print("layer2 ",y)





layer1  [[-0.25369039 -0.28099815 -1.4538666  -0.25293962 -0.21483605 -0.54354653
  -1.49392832 -0.3927023 ]
 [ 0.09384082 -0.11151222  0.07870701 -0.09105933 -0.01117716 -0.13619848
   0.01555215  0.0067789 ]
 [-1.61422465 -0.73459473 -1.16729062 -0.77619526 -0.59014887 -0.47479511
  -1.49448861 -0.99691436]
 [-0.50887543  0.06079215 -0.44940383  0.0142107  -0.10328744  0.14694842
  -0.39203272 -0.22584779]
 [ 1.99745034  0.71970914  1.15766984  0.79688702  0.65728024  0.31787385
   1.48499018  1.12839255]]
layer1  (5, 8)
layer2  [[0.90727297]
 [1.34273512]
 [0.7904693 ]
 [1.30013383]
 [1.94776974]]


In [ ]:
import numpy as np
np.arange(1,101)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [7]:
import numpy as np
# import matplotlib.pyplot as plt

np.random.seed(42)

# ── Step 1: Create correlated 2D data ──────────────────────────
X = np.random.randn(100, 2)
X[:, 1] = X[:, 0] * 0.9 + X[:, 1] * 0.3   # make correlated
print(f"Data shape: {X.shape}")              # (100, 2)

# ── Step 2: Mean-center the data ───────────────────────────────
X_mean = X - X.mean(axis=0)                 # subtract column means
print(f"Mean after centering: {X_mean.mean(axis=0).round(5)}")  # ~[0, 0]

# ── Step 3: Compute covariance matrix ──────────────────────────
# Cov = (Xᵀ @ X) / (n-1)
n = X_mean.shape[0]
cov = (X_mean.T @ X_mean) / (n - 1)
print(f"Covariance matrix:\n{cov.round(3)}")
# [[1.01  0.93]
#  [0.93  0.95]]

# ── Step 4: Eigendecomposition ─────────────────────────────────
eigenvalues, eigenvectors = np.linalg.eig(cov)
print(f"Eigenvalues:  {eigenvalues.round(3)}")   # [1.91, 0.05]
print(f"Eigenvectors:\n{eigenvectors.round(3)}")

# ── Step 5: Sort by largest eigenvalue ─────────────────────────
idx = np.argsort(eigenvalues)[::-1]             # descending order
eigenvalues  = eigenvalues[idx]
eigenvectors = eigenvectors[:, idx]
print(f"Sorted eigenvalues: {eigenvalues.round(3)}")

# ── Step 6: Project data onto top-1 principal component ────────
W = eigenvectors[:, :1]                         # top eigenvector (2,1)
X_pca = X_mean @ W                              # (100,2)@(2,1) → (100,1)
print(f"Projected shape: {X_pca.shape}")         # (100, 1)

# ── Step 7: Variance explained ─────────────────────────────────
var_explained = eigenvalues / eigenvalues.sum()
print(f"Variance explained: {(var_explained*100).round(1)}%")
# [97.4%, 2.6%]  → PC1 captures almost everything!
# ```

# ---/

### What each step does
# ```
# Step 1 → raw data         (100, 2)  — 100 samples, 2 features
# Step 2 → center at 0      (100, 2)  — remove mean so origin = data center
# Step 3 → covariance       (2, 2)    — how features vary together
# Step 4 → eigendecomp      values+vectors — find "stretch directions"
# Step 5 → sort             biggest eigenvalue = most variance = PC1
# Step 6 → project          (100, 1)  — compress 2D → 1D along PC1
# Step 7 → explained var    97.4%     — how much info we kept

Data shape: (100, 2)
Mean after centering: [-0. -0.]
Covariance matrix:
[[0.733 0.668]
 [0.668 0.699]]
Eigenvalues:  [1.384 0.048]
Eigenvectors:
[[ 0.716 -0.698]
 [ 0.698  0.716]]
Sorted eigenvalues: [1.384 0.048]
Projected shape: (100, 1)
Variance explained: [96.7  3.3]%
