In [4]:
import numpy as np

# Create a 1D NumPy array
arr = np.array([1, 2, 3, 4, 5])
# print(arr)
  
my_array=[[1,2,3],[4,5,6],[7,8,9]]
print(my_array)

np_array=np.array(my_array)
print(np_array)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
# np.arange(0,10,1)
print(np.arange(1,30,3))

[ 1  4  7 10 13 16 19 22 25 28]


In [ ]:
# zeros(rows,cols)
# ones(rows,cols)
print(np.zeros((3,4)))
print(np.ones((2,5)))
print(np.linspace(0,7,11)) # linspace(start, end, number of elements)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[0.  0.7 1.4 2.1 2.8 3.5 4.2 4.9 5.6 6.3 7. ]


In [17]:
np.eye(4)  # identity matrix of size 4x4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.random.rand(1)  # 3x3 matrix with random values between 0 and 1

array([[0.19349323, 0.12768084, 0.6253313 , 0.8430674 ],
       [0.40419574, 0.34103794, 0.68344876, 0.11677218],
       [0.80024046, 0.55626188, 0.47217339, 0.61451986]])

In [259]:
np.random.rand(3,3)  # 3x3 matrix with random values between 0 and 1

array([[0.08010354, 0.60721627, 0.6308467 ],
       [0.37794193, 0.01324101, 0.84221941],
       [0.38493775, 0.55166585, 0.71053814]])

In [ ]:
# np.random.randn(2,3)  # 2x3 matrix with values from standard normal distribution
# np.random.randint(0,10,(3,3))  # random integers between 1 and 10 in a 3x3 matrix

array([[ 0.70964518,  0.41350295,  0.73719112],
       [-0.41381345,  0.16940799, -2.33410139]])

In [1]:
# np.random.rand(43)  # 3x3 matrix with random values between 0 and 1
np.random.seed(5)
# 2x3 matrix with values from standard normal distribution

NameError: name 'np' is not defined

In [38]:
np.random.seed(101)

In [40]:
arr=np.arange(0,20)
arr.reshape(4,5)



array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
ranarr=np.random.randint(0,100,10)
print(ranarr)
ranarr.min()
# ranarr.argmax()
ranarr.argmax()
# ranarr.mean()
# ranarr.reshape(2,5)
ranarr.max()
ranarr.min()
ranarr.dtype




[71 20 27 75  5 49 86 89 63 82]


TypeError: 'tuple' object is not callable

In [60]:
arr
arr.shape
arr.reshape(5,4)
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [67]:
#Indexing the Slicing

arr=np.arange(1,11)
print(arr)
arr[5]


[ 1  2  3  4  5  6  7  8  9 10]


np.int64(6)

In [77]:
arr[1:5]
arr[0:5]
arr[:-1]
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [83]:
art=np.arange(1,11)
art[1:5]=99
art
broadcasting=art.copy()
broadcasting[:]=1000
print(broadcasting)
print(arr)

[1000 1000 1000 1000 1000 1000 1000 1000 1000 1000]
[100 100 100 100 100   6   7   8   9  10]


In [ ]:
# 2 dimnsional array
arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])
print(arr_2d)
# arr_2d[1]
# arr_2d[0][0]
# arr_2d.shape #show dimensions
# arr_2d[0,2] 
# arr_2d[:211,1:] #[:n ISKA MATLAB HAI :N print kro index n se pahle jo ayega ,]
            #[n: Iska matlab hai n aur uske baad index n ke baad ju bhi ayega print kro]
# Conditional selection
bool_arr=arr_2d < 4

arr_2d[bool_arr]

arr_2d[arr_2d>10]


[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


array([15, 20, 25, 30, 35, 40, 45])

In [235]:
add_arr=np.arange(0,11)
add_arr
add_arr + add_arr
add_arr * add_arr
add_arr - add_arr
arr/arr
1/arr
np.sqrt(add_arr)
np.sin(add_arr)
# np.log(add_arr)
np.append(add_arr,arr)
add_arr.max()
add_arr.min()
add_arr.var()
arr2d=np.arange(0,10).reshape(5,2)
arr2d



array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [253]:
arr2d.sum(axis=0) #operatoins across the rows 
# arr2d.sum(axis=1) #operations across the column

even_arr=np.arange(0,9).reshape(3,3)
# print(even_arr)
# arr_dim=even_arr/3
# try_dim=arr.reshape(3,3)
print(even_arr)
even_arr.shape


[[0 1 2]
 [3 4 5]
 [6 7 8]]


(3, 3)

In [ ]:

arr=np.arange(1,101)/100
ev=arr.reshape(10,10)
print(ev)

array([0.69528996])

In [ ]:
import pandas as pd
import numpy as np 
np.arange(100)


: 